### ISSUE TITLE
Improvements to the privileged UX implementation

### ISSUE THREAD

**Issue by jonathanmayer** [citp/news-disinformation-study#55]
- [ ] Refactor the privileged implementation into a namespace (e.g., `WebScience.Privileged`) that's clearly identified and that we can easily remove for test deployments that aren't privileged.
- [ ] Add more documentation to the privileged popup implementation.
- [ ] Reorganize the privileged popup code for simplicity and to avoid repetition. Probably the thing to do is create a module that exposes two functions (one for surveys, one for consent, each with the options we'll likely want to adjust), and then both of those functions call the same underlying privileged popup function.

**Comment by akohlbre** [comment]
Closing since we're no longer using privileged code.
