### ISSUE TITLE
Optimize the timeouts in measurement content scripts

### ISSUE THREAD

**Issue by jcchuang** [citp/news-disinformation-study#77]
https://github.com/citp/news-disinformation-study/blob/2d611b09fd6ed83676bc762a4e7f5521ffb5d6e2/WebScience/Measurements/content-scripts/pageDepth.js#L26

**Comment by jonathanmayer** [comment]
We're considering optimizations for the content script timers that we use for measuring page depth (in `pageNavigation.js`) and links in the DOM (in `linkExposure.js`).
* Measure page depth with a throttled `onscroll` listener (i.e., set a timer to check the scroll depth when `onscroll` fires and there isn't already a timer set).
* Only tick the timer for measuring links when the page has user attention.

**Comment by jonathanmayer** [comment]
Adding this issue to the `web-science` repo, closing here.
