### ISSUE TITLE
Find and remove all study-specific code from WebScience

### ISSUE THREAD

**Issue by akohlbre** [citp/news-disinformation-study#80]
- `AggregateStatistics` should be in the study code directory
- `UserSurvey.js` is being rewritten, but the current version has some hardcoded study-specific values

**Comment by jonathanmayer** [comment]
I removed `AggregateStatistics` from WebScience: https://github.com/mozilla-rally/web-science/commit/92ee41cc928ab1018c04730a5a58f719f1ea7b63

The `userSurvey` issue is on the `web-science` repo: https://github.com/mozilla-rally/web-science/issues/10
