### ISSUE TITLE
Convert `SocialMediaActivity` to use Events

### ISSUE THREAD

**Issue by akohlbre** [citp/news-disinformation-study#81]
- Update `Events` to support optionally-blocking events
- Use new blocking events within `SocialMediaActivity`
- Update `SocialMediaLinkSharing` to subscribe to SMA's events

**Comment by jonathanmayer** [comment]
> Update `Events` to support optionally-blocking events

A generic approach would be to allow specifying a listener return value callback in `Events`. We currently ignore listener return values. A blocking listener could just return a special value, similar to `webRequests.BlockingResponse`.

**Comment by jonathanmayer** [comment]
Closing this issue here, it's included in: https://github.com/mozilla-rally/web-science/issues/8
