### ISSUE TITLE
Document or find replacement for Ngrams.js

### ISSUE THREAD

**Issue by akohlbre** [citp/news-disinformation-study#85]
- If possible, find existing library to replace this file
- If not, add documentation to the existing file

**Comment by jonathanmayer** [comment]
Per @benjaminhkaiser, this code is from the `simplengrams` package.

https://www.npmjs.com/package/simplengrams
https://github.com/phughesmcr/SimpleNGrams

Looks like version 2.0.x; there are breaking API changes in 3.x.

As a first step, we should replace `Ngrams.js` with an NPM package dependency. We should eventually migrate to the current version of a more actively maintained toolkit, like `natural`.

https://www.npmjs.com/package/natural
https://github.com/NaturalNode/natural/blob/master/lib/natural/classifiers/classifier.js

**Comment by jonathanmayer** [comment]
Closing here, reopening on the `web-science` repo.
