### ISSUE TITLE
Separate Repository?

### ISSUE THREAD

**Issue by knowtheory** [citp/news-disinformation-study#86]
As of right now, we are managing two separate extensions with increasingly diverging code bases between the Ion News & Disinfo Study and the upcoming Rally News & Disinfo Study.

This presents a host of logistical issues (particularly how to communicate to addons reviewers the scope of this repository and what to look at).  Should we look at splitting one or the other of the Ion or Rally studies off into their own repository?

**Comment by jonathanmayer** [comment]
On our end, the consensus was to wind down the Ion study when we spin up the Rally study. Perhaps we should merge the `rally-prep` branch into the default branch when that happens? One study, one repo.

**Comment by akohlbre** [comment]
Discussed with JM -- I renamed `rally-prep` to `main` and `master` to `ion-study`, and made the new `main` the default branch. So, `ion-study` is there if we want to check what the last state of that version was, and otherwise `main` is the new Rally study.
