### ISSUE TITLE
Study is using telemetry API directly rather than Rally.js api

### ISSUE THREAD

**Issue by knowtheory** [citp/news-disinformation-study#87]
Hey!  The study [is still using the telemetry API directly](https://github.com/citp/news-disinformation-study/blob/685870aa90ae6e12b6cfe1707396713e2522776f/study/EventHandling.js#L130-L131), and instead should be using [the `sendPing` function available in Rally.js](https://github.com/mozilla-rally/rally-core-addon/blob/master/support/rally.js#L213)

**Comment by knowtheory** [comment]
@Dexterp37 & I also wanted to double check that the first link above is the location through which all data is submitted in the study.  I did a quick search for `telemetry.` and couldn't find any other instances, but wanted to confirm with the CITP team.

**Comment by akohlbre** [comment]
Closed by 25df79b. We indeed only submit pings from that one call in `EventHandling`, so I switched that one out and we should be good to go now.
