### ISSUE TITLE
Restricting private browsing mode

### ISSUE THREAD

**Issue by knowtheory** [citp/news-disinformation-study#90]
Given [the changes that have landed in Firefox release](https://bugzilla.mozilla.org/show_bug.cgi?id=1691144), can `"incognito": "not_allowed"` be added to the manifest?

Is incognito mode handling necessary at this point?

**Comment by jonathanmayer** [comment]
> Given [the changes that have landed in Firefox release](https://bugzilla.mozilla.org/show_bug.cgi?id=1691144), can `"incognito": "not_allowed"` be added to the manifest?

Yep! We should also bump the minimum Firefox version. Thanks again to @Dexterp37 for shepherding this patch.

> Is incognito mode handling necessary at this point?

I think we might as well leave the private browsing functionality in WebScience. We've already implemented it, and a study in future involving private browsing mode (with _very_ clear consent, possibly outside Rally) might be desirable.
